export const defaultCategories = [
  // Income Categories
  {
    id: "account-initiated",
    name: "Account Added",
    type: "INCOME",
    color: "#4caf50",
    icon: "AccountBalance",
  },
  {
    id: "salary",
    name: "Salary",
    type: "INCOME",
    color: "#22c55e",
    icon: "Wallet",
  },
  {
    id: "freelance",
    name: "Freelance",
    type: "INCOME",
    color: "#06b6d4",
    icon: "Laptop",
  },
  {
    id: "investments",
    name: "Investments",
    type: "INCOME",
    color: "#6366f1",
    icon: "TrendingUp",
  },
  {
    id: "business",
    name: "Business",
    type: "INCOME",
    color: "#ec4899",
    icon: "Building",
  },
  {
    id: "rental",
    name: "Rental",
    type: "INCOME",
    color: "#f59e0b",
    icon: "Home",
  },
  {
    id: "other-income",
    name: "Other Income",
    type: "INCOME",
    color: "#64748b",
    icon: "Plus",
  },
  {
    id: "cashback",
    name: "Cashback",
    type: "INCOME",
    color: "#10b981",
    icon: "CreditCard",
  },
  {
    id: "rewards",
    name: "Rewards",
    type: "INCOME",
    color: "#a855f7",
    icon: "Star",
  },
  {
    id: "grants",
    name: "Grants",
    type: "INCOME",
    color: "#3b82f6",
    icon: "HandCoins",
  },
  {
    id: "gifts-received",
    name: "Gifts Received",
    type: "INCOME",
    color: "#facc15",
    icon: "Gift",
  },
  {
    id: "refunds",
    name: "Refunds",
    type: "INCOME",
    color: "#60a5fa",
    icon: "RotateCcw",
  },
  {
    id: "tax-return",
    name: "Tax Return",
    type: "INCOME",
    color: "#0ea5e9",
    icon: "FileText",
  },
  {
    id: "dividends",
    name: "Dividends",
    type: "INCOME",
    color: "#14b8a6",
    icon: "LineChart",
  },
  {
    id: "lottery",
    name: "Lottery Winnings",
    type: "INCOME",
    color: "#facc15",
    icon: "Gift",
  },
  {
    id: "royalties",
    name: "Royalties",
    type: "INCOME",
    color: "#f472b6",
    icon: "Music",
  },
  {
    id: "resale",
    name: "Resale",
    type: "INCOME",
    color: "#fb7185",
    icon: "ShoppingCart",
  },
  {
    id: "consulting",
    name: "Consulting",
    type: "INCOME",
    color: "#8b5cf6",
    icon: "Users",
  },
  {
    id: "rental-equipment",
    name: "Equipment Rental",
    type: "INCOME",
    color: "#22d3ee",
    icon: "Camera",
  },
  {
    id: "affiliate",
    name: "Affiliate Income",
    type: "INCOME",
    color: "#4ade80",
    icon: "Link",
  },
  {
    id: "tips",
    name: "Tips",
    type: "INCOME",
    color: "#34d399",
    icon: "Coins",
  },
  {
    id: "bonus",
    name: "Bonus",
    type: "INCOME",
    color: "#f59e0b",
    icon: "Sparkles",
  },
  {
    id: "reimbursements",
    name: "Reimbursements",
    type: "INCOME",
    color: "#7c3aed",
    icon: "ClipboardList",
  },
  {
    id: "side-hustle",
    name: "Side Hustle",
    type: "INCOME",
    color: "#0f766e",
    icon: "Activity",
  },
  {
    id: "gratuity",
    name: "Gratuity",
    type: "INCOME",
    color: "#6366f1",
    icon: "Handshake",
  },
  {
    id: "rent-back",
    name: "Rent Payback",
    type: "INCOME",
    color: "#dc2626",
    icon: "Building2",
  },
  {
    id: "stock-sale",
    name: "Stock Sale",
    type: "INCOME",
    color: "#3b82f6",
    icon: "TrendingUp",
  },
  {
    id: "cashback",
    name: "Cashback",
    type: "INCOME",
    color: "#4ade80",
    icon: "Wallet",
  },
  {
    id: "youtube-income",
    name: "YouTube Income",
    type: "INCOME",
    color: "#ef4444",
    icon: "Youtube",
  },
  {
    id: "podcast-income",
    name: "Podcast Income",
    type: "INCOME",
    color: "#6366f1",
    icon: "Mic",
  },
  {
    id: "course-sale",
    name: "Course Sales",
    type: "INCOME",
    color: "#0ea5e9",
    icon: "BookOpen",
  },
  {
    id: "blogging",
    name: "Blogging Income",
    type: "INCOME",
    color: "#f59e0b",
    icon: "PenLine",
  },
  {
    id: "residuals",
    name: "Residuals",
    type: "INCOME",
    color: "#a78bfa",
    icon: "RefreshCcw",
  },
  {
    id: "ad-revenue",
    name: "Ad Revenue",
    type: "INCOME",
    color: "#e879f9",
    icon: "Megaphone",
  },
  {
    id: "grants",
    name: "Grants",
    type: "INCOME",
    color: "#10b981",
    icon: "Banknote",
  },
  {
    id: "inheritance",
    name: "Inheritance",
    type: "INCOME",
    color: "#8b5cf6",
    icon: "Gem",
  },
  {
    id: "insurance-claim",
    name: "Insurance Claim",
    type: "INCOME",
    color: "#facc15",
    icon: "Shield",
  },
  {
    id: "rent-deposit-return",
    name: "Rent Deposit Return",
    type: "INCOME",
    color: "#0f766e",
    icon: "Home",
  },
  {
    id: "gambling",
    name: "Gambling Winnings",
    type: "INCOME",
    color: "#f97316",
    icon: "Dice5",
  },
  {
    id: "donations-received",
    name: "Donations Received",
    type: "INCOME",
    color: "#f43f5e",
    icon: "HandHeart",
  },
  {
    id: "refunds",
    name: "Refunds",
    type: "INCOME",
    color: "#6ee7b7",
    icon: "Undo",
  },
  {
    id: "cash-gifts",
    name: "Cash Gifts",
    type: "INCOME",
    color: "#fb7185",
    icon: "Gift",
  },
  {
    id: "refund-tax",
    name: "Tax Refund",
    type: "INCOME",
    color: "#fcd34d",
    icon: "FileDollarSign",
  },
  {
    id: "rental-income-property",
    name: "Property Rental",
    type: "INCOME",
    color: "#f97316",
    icon: "Building",
  },
  {
    id: "partnership-income",
    name: "Partnership Profit",
    type: "INCOME",
    color: "#60a5fa",
    icon: "Handshake",
  },
  {
    id: "ebook-sales",
    name: "E-book Sales",
    type: "INCOME",
    color: "#06b6d4",
    icon: "FileText",
  },
  {
    id: "merch-sales",
    name: "Merchandise Sales",
    type: "INCOME",
    color: "#ec4899",
    icon: "Tshirt",
  },

  // Expense Categories
  {
    id: "housing",
    name: "Housing",
    type: "EXPENSE",
    color: "#ef4444",
    icon: "Home",
    subcategories: ["Rent", "Mortgage", "Property Tax", "Maintenance"],
  },
  {
    id: "transportation",
    name: "Transportation",
    type: "EXPENSE",
    color: "#f97316",
    icon: "Car",
    subcategories: ["Fuel", "Public Transport", "Maintenance", "Parking"],
  },
  {
    id: "groceries",
    name: "Groceries",
    type: "EXPENSE",
    color: "#84cc16",
    icon: "Shopping",
  },
  {
    id: "utilities",
    name: "Utilities",
    type: "EXPENSE",
    color: "#06b6d4",
    icon: "Zap",
    subcategories: ["Electricity", "Water", "Gas", "Internet", "Phone"],
  },
  {
    id: "entertainment",
    name: "Entertainment",
    type: "EXPENSE",
    color: "#8b5cf6",
    icon: "Film",
    subcategories: ["Movies", "Games", "Streaming Services"],
  },
  {
    id: "food",
    name: "Food",
    type: "EXPENSE",
    color: "#f43f5e",
    icon: "UtensilsCrossed",
  },
  {
    id: "shopping",
    name: "Shopping",
    type: "EXPENSE",
    color: "#ec4899",
    icon: "ShoppingBag",
    subcategories: ["Clothing", "Electronics", "Home Goods"],
  },
  {
    id: "healthcare",
    name: "Healthcare",
    type: "EXPENSE",
    color: "#14b8a6",
    icon: "HeartPulse",
    subcategories: ["Medical", "Dental", "Pharmacy", "Insurance"],
  },
  {
    id: "education",
    name: "Education",
    type: "EXPENSE",
    color: "#6366f1",
    icon: "GraduationCap",
    subcategories: ["Tuition", "Books", "Courses"],
  },
  {
    id: "personal",
    name: "Personal Care",
    type: "EXPENSE",
    color: "#d946ef",
    icon: "Smile",
    subcategories: ["Haircut", "Gym", "Beauty"],
  },
  {
    id: "travel",
    name: "Travel",
    type: "EXPENSE",
    color: "#0ea5e9",
    icon: "Plane",
  },
  {
    id: "insurance",
    name: "Insurance",
    type: "EXPENSE",
    color: "#64748b",
    icon: "Shield",
    subcategories: ["Life", "Home", "Vehicle"],
  },
  {
    id: "gifts",
    name: "Gifts & Donations",
    type: "EXPENSE",
    color: "#f472b6",
    icon: "Gift",
  },
  {
    id: "bills",
    name: "Bills & Fees",
    type: "EXPENSE",
    color: "#fb7185",
    icon: "Receipt",
    subcategories: ["Bank Fees", "Late Fees", "Service Charges"],
  },
  {
    id: "pets",
    name: "Pet Care",
    type: "EXPENSE",
    color: "#34d399",
    icon: "PawPrint",
    subcategories: ["Vet", "Food", "Grooming", "Toys"],
  },
  {
    id: "subscriptions",
    name: "Subscriptions",
    type: "EXPENSE",
    color: "#fbbf24",
    icon: "Newspaper",
    subcategories: ["Netflix", "Spotify", "Magazines", "Software"],
  },
  {
    id: "events",
    name: "Events",
    type: "EXPENSE",
    color: "#f87171",
    icon: "Calendar",
    subcategories: ["Concerts", "Weddings", "Birthdays"],
  },
  {
    id: "investments-expense",
    name: "Investment Outflows",
    type: "EXPENSE",
    color: "#4ade80",
    icon: "Banknote",
    subcategories: ["Stock Purchase", "Mutual Funds", "Crypto"],
  },
  {
    id: "childcare",
    name: "Childcare",
    type: "EXPENSE",
    color: "#fb923c",
    icon: "Baby",
    subcategories: ["School", "Babysitter", "Toys"],
  },
  {
    id: "loans",
    name: "Loan Payments",
    type: "EXPENSE",
    color: "#e879f9",
    icon: "TrendingDown",
    subcategories: ["Student Loan", "Car Loan", "Personal Loan"],
  },
  {
    id: "emergency",
    name: "Emergency Fund",
    type: "EXPENSE",
    color: "#e11d48",
    icon: "AlertTriangle",
  },

  {
    id: "other-expense",
    name: "Other Expenses",
    type: "EXPENSE",
    color: "#94a3b8",
    icon: "MoreHorizontal",
  },
  {
    id: "furnishing",
    name: "Furnishing",
    type: "EXPENSE",
    color: "#f43f5e",
    icon: "Lamp",
    subcategories: ["Furniture", "Decor", "Repairs"],
  },
  {
    id: "legal",
    name: "Legal Services",
    type: "EXPENSE",
    color: "#7e22ce",
    icon: "Gavel",
  },
  {
    id: "hobbies",
    name: "Hobbies",
    type: "EXPENSE",
    color: "#38bdf8",
    icon: "Palette",
    subcategories: ["Crafts", "Board Games", "Reading"],
  },
  {
    id: "home-office",
    name: "Home Office",
    type: "EXPENSE",
    color: "#10b981",
    icon: "Briefcase",
    subcategories: ["Desk", "Stationery", "Chair"],
  },
  {
    id: "maintenance",
    name: "Maintenance",
    type: "EXPENSE",
    color: "#d97706",
    icon: "Wrench",
  },
  {
    id: "fun",
    name: "Fun & Leisure",
    type: "EXPENSE",
    color: "#c084fc",
    icon: "Gamepad",
  },
  {
    id: "charity",
    name: "Charity",
    type: "EXPENSE",
    color: "#a3e635",
    icon: "Heart",
  },
  {
    id: "alcohol",
    name: "Alcohol",
    type: "EXPENSE",
    color: "#f43f5e",
    icon: "Beer",
  },
  {
    id: "smoking",
    name: "Smoking",
    type: "EXPENSE",
    color: "#f87171",
    icon: "Flame",
  },
  {
    id: "laundry",
    name: "Laundry",
    type: "EXPENSE",
    color: "#60a5fa",
    icon: "Droplet",
  },
  {
    id: "atm-withdrawal",
    name: "ATM Withdrawal",
    type: "EXPENSE",
    color: "#fb923c",
    icon: "CreditCard",
  },
  {
    id: "security",
    name: "Home Security",
    type: "EXPENSE",
    color: "#0ea5e9",
    icon: "ShieldCheck",
  },
  {
    id: "subscriptions-software",
    name: "Software Subscriptions",
    type: "EXPENSE",
    color: "#06b6d4",
    icon: "Code2",
    subcategories: ["Figma", "VS Code Extensions", "Adobe"],
  },
  {
    id: "storage",
    name: "Storage",
    type: "EXPENSE",
    color: "#94a3b8",
    icon: "Box",
  },
  {
    id: "eco-friendly",
    name: "Eco-friendly Purchases",
    type: "EXPENSE",
    color: "#22c55e",
    icon: "Leaf",
  },
  {
    id: "parking",
    name: "Parking",
    type: "EXPENSE",
    color: "#f87171",
    icon: "ParkingMeter",
  },
  {
    id: "pet-food",
    name: "Pet Food",
    type: "EXPENSE",
    color: "#4ade80",
    icon: "Dog",
  },
  {
    id: "streaming",
    name: "Streaming Services",
    type: "EXPENSE",
    color: "#60a5fa",
    icon: "PlayCircle",
  },
  {
    id: "celebrations",
    name: "Celebrations",
    type: "EXPENSE",
    color: "#eab308",
    icon: "PartyPopper",
  },
  {
    id: "makeup",
    name: "Makeup & Beauty",
    type: "EXPENSE",
    color: "#f472b6",
    icon: "Sparkle",
  },
  {
    id: "baby-supplies",
    name: "Baby Supplies",
    type: "EXPENSE",
    color: "#fb923c",
    icon: "Baby",
  },
  {
    id: "education-kids",
    name: "Kid's Education",
    type: "EXPENSE",
    color: "#a78bfa",
    icon: "School",
  },
  {
    id: "fines",
    name: "Fines & Penalties",
    type: "EXPENSE",
    color: "#ef4444",
    icon: "Ban",
  },
  {
    id: "garden",
    name: "Gardening",
    type: "EXPENSE",
    color: "#22c55e",
    icon: "Leaf",
  },
  {
    id: "event-tickets",
    name: "Event Tickets",
    type: "EXPENSE",
    color: "#8b5cf6",
    icon: "Ticket",
  },
  {
    id: "coffee",
    name: "Coffee",
    type: "EXPENSE",
    color: "#b45309",
    icon: "Coffee",
  },
  {
    id: "cosmetics",
    name: "Cosmetics",
    type: "EXPENSE",
    color: "#f472b6",
    icon: "Brush",
  },
  {
    id: "tools",
    name: "Tools & Equipment",
    type: "EXPENSE",
    color: "#0f766e",
    icon: "Hammer",
  },
  {
    id: "debt-repayment",
    name: "Debt Repayment",
    type: "EXPENSE",
    color: "#f43f5e",
    icon: "RotateCcw",
  },
  {
    id: "therapy",
    name: "Therapy",
    type: "EXPENSE",
    color: "#6b7280",
    icon: "HeartHandshake",
  },
  {
    id: "grooming",
    name: "Pet Grooming",
    type: "EXPENSE",
    color: "#60a5fa",
    icon: "Scissors",
  },
  {
    id: "internet",
    name: "Internet",
    type: "EXPENSE",
    color: "#0284c7",
    icon: "Globe",
  },
  {
    id: "haircut",
    name: "Haircut",
    type: "EXPENSE",
    color: "#6366f1",
    icon: "Scissors",
  },
  {
    id: "music-subscription",
    name: "Music Subscriptions",
    type: "EXPENSE",
    color: "#a855f7",
    icon: "Music",
  },
  {
    id: "vehicle-service",
    name: "Vehicle Service",
    type: "EXPENSE",
    color: "#16a34a",
    icon: "Wrench",
  },
];

export const categoryColors = defaultCategories.reduce((acc, category) => {
  acc[category.name] = category.color;

  return acc;
}, {});
